//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUPITCHAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAT_MESSAGES
    {
        public long Id { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string Message { get; set; }
        public Nullable<int> IconID { get; set; }
        public Nullable<long> SenderID { get; set; }
        public Nullable<byte> Mark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
